### ISSUE TITLE
state修改后在内存中无效

### ISSUE THREAD

**Issue by cc10vv2007** [GameFrameX/GameFrameX.Server#4]
基础情况 : 客户端加了一个GM指令用于添加道具
实际问题 :  客户端发送GM(add item xx xx) 对bagstate.itemMap.Add(id , count)  ,   第二次在发送一次GM 对bagstate.itemMap修改时,发现bagstate.itemMap内无数据.

**Comment by AlianBlank** [comment]
请提供一下实例代码。我需要复现测试
