### ISSUE TITLE
State先Add再Update会报空，必须经过Find才可以

### ISSUE THREAD

**Issue by SimpleEve** [GameFrameX/GameFrameX.Server#7]
如果一个State是在代码里new的，调用了Save，而不是Find，后面用这个State再去Update，就会报错。需要手动调用一下Find才可以。
![984e55d2adb8eadc364e22926c11bf1](https://github.com/user-attachments/assets/f05499c5-ed68-443d-b04d-d01e59d35f34)

应该是_stateHash只有在Find的时候才会被初始化
![f1a9244b78dac5514dd511a40e2b390](https://github.com/user-attachments/assets/03cbae3e-b72e-4811-92e7-eedd12ebddb3)

**Comment by AlianBlank** [comment]
请不要使用new 的方式创建一个State对象。你可以Find(0) 的方式获得一个对象。然后修改他的值。
